# Generated by Django 5.0.7 on 2024-08-01 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_max', models.IntegerField()),
                ('capacidad_uso', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('espacio_disponible', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bodega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField()),
                ('id_bodega', models.ForeignKey(blank=True, db_column='id_bodega', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bodega')),
                ('id_producto', models.OneToOneField(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.productos')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.productos')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
    ]
